language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
install:
  - rustup component add rustfmt-preview
script:
  - cargo fmt -- --check
  - cargo build --verbose --all
  - cargo test --verbose --all