[package]
name = "particles"
version = "0.1.0"
authors = ["theAzack9 <robin@cavachi.be>", "stisol", "vegit"]
build = "build.rs"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
noise = "0.5.1"
rand = "0.5"

[target.'cfg(not(any(target_arch = "wasm32")))'.dependencies]
gl = "0.10.0"
glutin = "0.17"


[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4.0"
stdweb-derive = "0.4.0"

[build-dependencies]
webgl_generator = "0.1.0"