//! Very inspired from kiss3d's implementation of window and context
//! link: https://github.com/sebcrozet/kiss3d

pub use self::webgl_window::WebGLWindow;

// Ignore warnings in autogenerated bindings
#[allow(unused_parens)]
#[allow(dead_code)]
#[cfg(target_arch = "wasm32")]
mod webgl_bindings;

mod webgl_window;

pub use self::webgl_window::{
    UniformLocation, GLEnum, GLsizeiptr, GLintptr, GLBuffer, GLShader, GLProgram, GLVertexArray, GLUint
};