/*
 * Very inspired from kiss3d's implementation of window and context
 * link: https://github.com/sebcrozet/kiss3d
 */
#![allow(unused_results)]

// Ignore warnings in autogenerated bindings
#[allow(unused_parens)]
#[allow(dead_code)]
#[cfg(target_arch = "wasm32")]
mod webgl_bindings;

use shaders::ShaderType;

use stdweb::unstable::TryInto;
use stdweb::web::html_element::CanvasElement;
use stdweb::web::{document, IParentNode, TypedArray};
use stdweb::Value;

use std::{mem};

use na::{Matrix4};

use context::{GlPrimitive, GlPrimitiveArray};

use Program;
use Shader;
use AbstractContext;
use NativeBuffer;
use Context;

use self::webgl_bindings::{
    WebGLRenderingContext, WebGLBuffer, WebGLProgram,
    WebGLShader, WebGLUniformLocation
};

pub use self::webgl_bindings::{
    GLenum, GLintptr, GLsizeiptr
};

pub type GLShader = WebGLShader;
pub type GLProgram = WebGLProgram;
pub type UniformLocation = WebGLUniformLocation;
pub type GLEnum = GLenum;
pub type GLBuffer = WebGLBuffer;
pub type GLUint = u32;

lazy_static! {
    static ref CONTEXT: Context = WebGLContext::new();
}

pub struct WebGLContext {
    context: WebGLRenderingContext
}

impl WebGLContext {
    fn new() -> Self {
        stdweb::initialize();
        let canvas: CanvasElement = document()
            .query_selector("#canvas")
            .expect("No canvas found")
            .unwrap()
            .try_into()
            .unwrap();

        let context = js!(return @{canvas}.getContext("webgl", {alpha: false});).try_into().unwrap();
        WebGLContext { context }
    }
}

impl AbstractContext for WebGLContext {
    const FLOAT: u32 = WebGLRenderingContext::FLOAT;
    const COLOR_BUFFER_BIT: u32 = WebGLRenderingContext::COLOR_BUFFER_BIT;
    const VERTEX_SHADER: u32 = WebGLRenderingContext::VERTEX_SHADER;
    const FRAGMENT_SHADER: u32 = WebGLRenderingContext::FRAGMENT_SHADER;
    const ARRAY_BUFFER: u32 = WebGLRenderingContext::ARRAY_BUFFER;
    const ELEMENT_ARRAY_BUFFER: u32 = WebGLRenderingContext::ELEMENT_ARRAY_BUFFER;
    const STATIC_DRAW: u32 = WebGLRenderingContext::STATIC_DRAW;
    const DYNAMIC_DRAW: u32 = WebGLRenderingContext::STATIC_DRAW;
    const COMPILE_STATUS: u32 = WebGLRenderingContext::COMPILE_STATUS;
    const POINTS: u32 = WebGLRenderingContext::POINTS;
    const LINE_STRIP: u32 = WebGLRenderingContext::LINE_STRIP;
    const LINE_LOOP: u32 = WebGLRenderingContext::LINE_LOOP;
    const LINES: u32 = WebGLRenderingContext::LINES;
    const TRIANGLE_STRIP: u32 = WebGLRenderingContext::TRIANGLE_STRIP;
    const TRIANGLE_FAN: u32 = WebGLRenderingContext::TRIANGLE_FAN;
    const TRIANGLES: u32 = WebGLRenderingContext::TRIANGLES;
    const UNSIGNED_SHORT: u32 = WebGLRenderingContext::UNSIGNED_SHORT;

    fn get_context() -> &'static Context {
        &CONTEXT
    }
    fn clear_color(&self, r: f32, g: f32, b: f32, a: f32) {
        self.context.clear_color(r, g, b, a);
    }

    fn clear(&self, mask: u32) {
        self.context.clear(mask);
    }
    fn create_shader(&self, type_: ShaderType) -> Option<Shader> {
        match type_ {
            ShaderType::Vertex => self.context.create_shader(Self::VERTEX_SHADER),
            ShaderType::Fragment => self.context.create_shader(Self::FRAGMENT_SHADER),
        }
    }

    fn shader_source(&self, shader: &Shader, source: &str) {
        self.context.shader_source(shader, source);
    }

    fn compile_shader(&self, shader: &Shader) {
        self.context.compile_shader(shader);
    }

    fn delete_shader(&self, shader: &Shader) {
        self.context.delete_shader(Some(shader));
    }

    fn get_shader_parameter(&self, shader: &Shader, pname: GLEnum) -> Option<i32> {
        // TODO: Handle all value types?
        match self.context.get_shader_parameter(shader, pname) {
            Value::Number(n) => n.try_into().ok(),
            _ => None,
        }
    }

    fn get_shader_info_log(&self, shader: &Shader) -> Option<String> {
        self.context.get_shader_info_log(shader)
    }

    fn create_program(&self) -> Option<Program> {
        self.context.create_program()
    }

    fn attach_shader(&self, program: &Program, shader: &Shader) {
        self.context.attach_shader(program, shader);
    }

    fn link_program(&self, program: &Program) {
        self.context.link_program(program);
    }

    fn use_program(&self, program: &Program) {
        self.context.use_program(Some(program));
    }

    fn delete_program(&self, program: &Program) {
        self.context.delete_program(Some(program));
    }

    fn create_buffer(&self) -> Option<NativeBuffer> {
        self.context.create_buffer()
    }

    fn bind_buffer(&self, target: GLEnum, buffer: &NativeBuffer) {
        self.context.bind_buffer(target, Some(buffer));
    }

    fn buffer_data<T: GlPrimitive>(&self, target: GLEnum, data: &[T], usage: GLEnum) {
        match T::into(data) {
            GlPrimitiveArray::F32(data) => {
                let abuf = TypedArray::<f32>::from(data);
                self.context
                    .buffer_data_1(target, Some(&abuf.buffer()), usage);
            },
            GlPrimitiveArray::U16(data) => {
                let abuf = TypedArray::<u16>::from(data);
                self.context
                    .buffer_data_1(target, Some(&abuf.buffer()), usage);
            }
        }
    }

    fn delete_buffer(&self, buffer: &NativeBuffer) {
        self.context.delete_buffer(Some(buffer));
    }

    fn get_attrib_location(&self, program: &Program, name: &str) -> GLUint {
        self.context.get_attrib_location(program, name) as u32
    }

    fn vertex_attrib_pointer(
        &self,
        pointer: &GLUint,
        size: i32,
        type_: GLEnum,
        normalized: bool,
        stride: i32,
        offset: i32,
    ) {
        self.context.vertex_attrib_pointer(
            *pointer,
            size,
            type_,
            normalized,
            (stride * mem::size_of::<f32>() as i32) as i32,
            (offset * mem::size_of::<f32>() as i32) as GLintptr,
        ) // todo: offset as custom type
    }

    fn enable_vertex_attrib_array(&self, pointer: &GLUint) {
        self.context.enable_vertex_attrib_array(*pointer)
    }

    fn disable_vertex_attrib_array(&self, pointer: &GLUint) {
        self.context.disable_vertex_attrib_array(*pointer)
    }
    
    fn bind_attrib_location(&self, program: &Program, index: GLUint, name: &str) {
        self.context.bind_attrib_location(program, index, name)
    }

    fn get_uniform_location(&self, program: &Program, name: &str) -> UniformLocation {
        self.context.get_uniform_location(program, name).expect("Uniform location could not be found or does not exist")
    }

    fn uniform_matrix_4fv(&self, location: &UniformLocation, _size: i32, transpose: bool, matrix: &Matrix4<f32>) {
        self.context.uniform_matrix4fv(Some(location), transpose, matrix.as_slice())
    }

    fn draw_arrays(&self, type_: GLEnum, first: i32, count: i32) {
        self.context.enable(WebGLRenderingContext::BLEND);
        self.context.blend_func(
            WebGLRenderingContext::SRC_ALPHA,
            WebGLRenderingContext::ONE_MINUS_SRC_ALPHA,
        );
        self.context.draw_arrays(type_, first, count)
    }

    fn draw_elements(&self, mode: GLEnum, count: i32, type_: GLEnum, offset: GLintptr) {
        self.context.draw_elements(mode, count, type_, offset);
    }
}